title: Anupam Maiti
logo: /assets/img/myPic.png
description: Hello, I'm Anupam! 👋 I'm passionate about technology and have a positive outlook, always eager to grow and learn.
  <div> <a href="https://www.linkedin.com/in/anupam-maiti/">View My LinkedIn Profile</a> </div>

