title: Anupam Maiti
logo: /assets/img/myPic.png
description: Hello, I'm Anupam! 👋 I'm passionate about technology and have a positive outlook, always eager to grow and learn.
  <div> <a href="https://www.linkedin.com/in/anupam-maiti/">View My LinkedIn Profile</a> </div>
  <br>
  <a href="https://www.c-sharpcorner.com/members/awesome-anupam">
  <img src="https://www.c-sharpcorner.com/members/awesome-anupam/flair.png" width="260" height="58" alt="profile for Anupam C# Corner - A Social Community of Developers and Programmers" title="profile for Anupam at C# Corner - A Social Community of Developers and Programmers" />
  </a>

theme: jekyll-theme-minimal
