			<section id="header">
				<header>
					<span class="image avatar"><img src="/assets/img/myPic.png" alt="" /></span>
					<h1 id="logo"><a href="#">Anupam Maiti</a></h1>
				</header>
				<footer>
					<ul class="icons">
						<li><a href="https://www.linkedin.com/in/anupam-maiti/" class="icon brands fa-linkedin"><span class="label">LinkedIn</span></a></li>
						<li><a href="https://github.com/dynamicanupam" class="icon brands fa-github"><span class="label">Github</span></a></li>
						<li><a href="mailto:mailtoanupammaiti@gmail.com" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
					</ul>
				</footer>
			</section>
